/*CMD
  command:  /ccgenData
  help: 
  need_reply: false
  auto_retry_time: 
  folder: Fake Credit Card

  <<ANSWER

  ANSWER

  <<KEYBOARD

  KEYBOARD
  aliases: 
CMD*/

var result = JSON.parse(content)
var name = result.information.Name
var gender = result.information.Gender
var birthday = result.information.Birthday
var birthplace = result.information.Birthplace
var Zodi = result.information["Zodiac Sign"]
var address = result.information.Address
var company = result.information.Company
var phno = result.information["Phone Number"]
var vehicle = result.information.Vehicle
var ccno = result.CreditCard.CardNumber
var cvv = result.CreditCard["CVV"]
var exp = result.CreditCard["EXP"]
Bot.sendMessage(
  "*💳 Credit Card Generated \n 🤵‍♂️ Name:* " +
    name +
    " \n *🚻 Gender:* " +
    gender +
    " \n *🎂 Birthday:* " +
    birthday +
    " \n *❇️ Birthplace:* " +
    birthplace +
    " \n *♉️ Zodiac Sign:* " +
    Zodi +
    " \n *🏡 Address:* " +
    address +
    " \n *🏭 Company:* " +
    company +
    " \n *📞 Phone Number:* " +
    phno +
    " \n *🚙 Vehicle:* " +
    vehicle +
    " \n - - - - - - - - - - - - - - - - - - - - - - - - - \n *🔄 Credit Card Info 🔄* \n *☢️ CardNumber:* " +
    ccno +
    " \n *⛔️ CVV:* " +
    cvv +
    " \n *🛅 Expiry:* " +
    exp +
    " \n *🆔 Generated by @" +
    bot.name +
    "*"
)

