/*CMD
  command: /download
  help: 
  need_reply: true
  auto_retry_time: 
  folder: 
  answer: 👨‍💻 send YouTube Video Url To Download

  <<KEYBOARD

  KEYBOARD
  aliases: 
CMD*/

function validURL(url) {

  var regex = /^((?:https?:)?//)?((?:www|m).)?((?:youtube.com|youtu.be))(/(?:[w-]+?v=|embed/|v/)?)([w-]+)(S+)?$/

  return regex.test(url)

}



if (validURL(message)) {

Api.sendVideo({video: "https://coinsky.xp3.biz/api/youtube/download.php?url="+message+"", caption: "*⏳ Video Generated By @idrisiboy123*", parse_mode: "markdown"})

return

}else {
Bot.sendMessage("*Invalid YouTube Video Url or video Doesn't Exists*")
}
