/*CMD
  command: /text_to_voice
  help: 
  need_reply: true
  auto_retry_time: 
  folder: 
  answer:  *✍Send Your Message To Convert Into Voice*


  <<KEYBOARD

  KEYBOARD
  aliases: /text_to_voice@grouphelpmrbeebot, /ttovoice, /ttovoice@grouphelpmrbeebot
CMD*/

Api.sendChatAction({
  chat_id: chat.chatid,
  action: "upload_audio"
})
Api.sendChatAction({
  chat_id: chat.chatid,
  action: "upload_audio"
})
Api.sendChatAction({
  chat_id: chat.chatid,
  action: "upload_audio"
})

Bot.sendMessage("*Generating , it will take time*")
Api.sendAudio({
  audio: "https://lyciavoice.herokuapp.com/lycia?text=" + message + "&lang=en",
  caption:
    "\n\n*📝 Here Is Your Voice Message With Text: \n " +
    message +
    "\n\n🎙️ Generated By @" +
    bot.name +
    ".*",
  parse_mode: "Markdown",
  reply_markup: {
    inline_keyboard: [[{ text: "🚫 Close Tab", callback_data: "m" }]]
  },
  disable_web_page_preview: true
})

