/*CMD
  command: /logo
  help: 
  need_reply: true
  auto_retry_time: 
  folder: Logo
  answer: Send something to make a  logo..

  <<KEYBOARD

  KEYBOARD
  aliases: /logo@grouphelpmrbeebot
CMD*/

var buttons = [
[{title: "Next type", command: "/logo_2"}]
]
Bot.sendInlineKeyboard(buttons, "Click on Next type to create a\n  ☟different type of logo.☟")
// command post runs a command
// where the url is written opens a link:/

Api.sendPhoto({
  photo:
    "https://malfrafg.sirv.com/images.jfif?text=" +
    message +
    "&text.font.weight=extra-bold&text.size=80&text.font.style=italic&text.outline.width=10&text.outline.color=00000&text.position=center&text.font.family=Bitter&text.color=D90A08&text.outline.blur=10",
  caption:
    "*📝 Congrats! Your Logo Is Ready...\n\nGENERATED BY @" + bot.name + "*",
  parse_mode: "markdown"
})

